### ISSUE TITLE
Залить первоначальный проект

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KursRabTRPO#6]
В январе 19г, мы сдали Юрию Леонидовичу первоначальный проект, просьба залить его в этот репозиторий!

По выполнении отписаться в комментарий.

**Comment by Proffet78** [comment]
Срок выполнения до 04.06.19

**Comment by VinogradovAlexandr781227** [comment]
@Proffet78, задача выполнена, просьба проверить!

Спасибо, Саша

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, начальниха одобрил!
Просьба создать новую ветку под названием "TRPO.KP.v1.0" 
КАК СОЗДАШЬ, ЗАКРОЮ ЗАДАЧУ))

Спасибо, тимлид

**Comment by VinogradovAlexandr781227** [comment]
@Proffet78, ветка создана!

**Comment by Proffet78** [comment]
@VinogradovAlexandr781227, 
Задание принято - ЗАЧТЕНО!

Спасибо, тимлид
