### ISSUE TITLE
Создать google-disk для документов

### ISSUE THREAD

**Issue by Proffet78** [Proffet78/KursRabTRPO#8]
Создать гугл-диск для документов, сделать его доступным для всех у кого есть ссылка,ссылку прикрепить тут:

**ССЫЛКА НА google-disk** -  https://drive.google.com/drive/folders/16c5XUnGnyBdruK-CQEUzzfTd71Z4IQWO?usp=sharing

Поместить туда необходимое техническое задание. 

По выполнении отписаться в комментарий.

**Comment by GubanovAndrey** [comment]
Здравствуйте, @Proffet78 !

Создал диск, поместил туда документы! Просьба проверить!

Спасибо, Губанов Андрей

**Comment by Proffet78** [comment]
Здравствуйте, @GubanovAndrey !

Задание принято - ЗАЧТЕНО!

Спасибо, тимлид
